<?php

namespace Marando\Meeus\Nutation;

use \Marando\AstroDate\AstroDate;
use \Marando\Units\Angle;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 18:27:14.
 */
class NutationTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\Meeus\Nutation\Nutation::find
   * @see p.148, ex. 22.a
   */
  public function testFind() {
    $n = Nutation::find(AstroDate::parse('1987-Apr-10'));

    $this->assertEquals(-3.788 / 3600, $n->long->deg, 'Δψ', 1e-6);
    $this->assertEquals(+9.443 / 3600, $n->obli->deg, 'Δε', 1e-6);
  }

  /**
   * @covers Marando\Meeus\Nutation\Nutation::inRA
   * @see p.88, ex. 12.a
   */
  public function testInRA() {
    $inRA = Nutation::inRA(AstroDate::parse('1987-Apr-10'));
    $this->assertEquals(-0.2317, $inRA->sec, 'nRA', 1e-4);
  }

  /**
   * @covers Marando\Meeus\Nutation\Nutation::meanObliquity
   * @see p.148, ex. 22.a
   */
  public function testMeanObliquity() {
    $ε0 = Nutation::meanObliquity(AstroDate::parse('1987-Apr-10'));
    $this->assertEquals(Angle::dms(23, 26, 27.407), $ε0, 'ε0', 1e-3);
  }

  /**
   * @covers Marando\Meeus\Nutation\Nutation::trueObliquity
   * @see p.148, ex. 22.a
   */
  public function testTrueObliquity() {
    $ε = Nutation::trueObliquity(AstroDate::parse('1987-Apr-10'));
    $this->assertEquals(23, $ε->d, 'd');
    $this->assertEquals(26, $ε->m, 'm');
    $this->assertEquals(36.850, $ε->s, 's', 1e-2);
  }

}
