<?php

namespace Marando\Meeus\Nutation;

use \Marando\AstroDate\AstroDate;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 18:27:14.
 */
class NutationTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\Meeus\Nutation\Nutation::find
   */
  public function testFind() {
    $n = Nutation::find(AstroDate::parse('1987-Apr-10'));

    $this->assertEquals(-3.788 / 3600, $n->long->deg, 'Δψ', 1e-6);
    $this->assertEquals(+9.443 / 3600, $n->obli->deg, 'Δε', 1e-6);
  }

}
